#%RAML 1.0
title: product-api
baseUri: http://localhost:8081/products
/products:
  get:
    description: To get product
    responses:
      200:
        body:
          application/json:
            example:
              {
                "productID": "12345678",
                "productName": "Mulesoft Dev",
                "productProvider": "Udemy",
                "productDescription": "This is regarding mulesoft course"
              }